# Generated by Django 3.1.4 on 2020-12-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='image',
        ),
    ]
