# Generated by Django 3.1.4 on 2020-12-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(upload_to='static/discount')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Sox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.TextField()),
                ('image', models.ImageField(upload_to='static/sox')),
                ('fabrics', models.TextField()),
                ('size', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='shop.discount')),
            ],
            options={
                'verbose_name': 'Sox',
                'verbose_name_plural': 'Sox',
            },
        ),
    ]
