# Generated by Django 3.1.4 on 2020-12-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sox',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
